config/routes.rb
Rails.application.routes.draw do
  root :to => "scripts#home"
  resources :scripts 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
  belongs_to :script
end

app/models/script.rb
class Script < ApplicationRecord
  attr_accessor :virtual_user
  DEFAULT_VALUE = 0

  belongs_to :user
  has_one :point, dependent: :destroy

  after_create :default_point_for_essay

  private

  def default_point_for_essay
    Point.create(
      value: DEFAULT_VALUE,
      user_id: self.user&.id,
      script_id: id
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, uniqueness: true, presence: true

    has_many :scripts,  dependent: :destroy
    has_many :points,  dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController

  before_action :set_user, only: %i[create]

  def home
  end

  def index
    @scripts = Script.all
  end

  def show
    @script = Script.find(params[:id])
  end

  def new
    @script = Script.new
  end

  def create
    @script = Script.new(script_params)
    @script.user = @user


    if @script.save
      redirect_to @script
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @script = Script.find(params[:id])
  end

  def update
    @script = Script.find(params[:id])

    if @script.update(script_params)
      redirect_to @script
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @script = Script.find(params[:id])
    @script.destroy

    redirect_to scripts_path, status: :see_other
  end

  private
    def script_params
      params.require(:script).permit(:script_type, :content)
    end

    def set_user
      @user = User.create!(name: params[:script][:virtual_user])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EssayProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scripts/_form.html.erb
  <%= form_with model: @script do |form| %>
  
  <%if params[:action].eql?('new')%>
    <div>
      <%= form.label :virtual_user, "Enter username" %><br>
      <%= form.text_area :virtual_user %>
      <% @script.errors.full_messages_for(:virtual_user).each do |message| %>
      
        <div><%= message %></div>
      <% end %>
    </div>
  <%end%>

  <div>
    <%= form.hidden_field :script_type, value: "essay" %><br>
    <%= form.label :content, "Write your essay below" %><br>
    <%= form.text_area :content, size: "100" %>
    <% @script.errors.full_messages_for(:content).each do |message| %>
    
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Submit your Essay"%>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<h1>New Essay</h1>
<%= render "form", grade: @grade %>

app/views/scripts/home.html.erb
<h1> Welcome </h1>

<div>
<%= link_to "Click Here to write new Essay", new_script_path%>
<br><br><br>
</div>

<div>
<%= link_to "Click Here to see all Essay", scripts_path%>
</div>

app/views/scripts/index.html.erb
<h1>All Essays</h1>

<% if @scripts.present? %>
  <ul>
  <% @scripts.each do |script| %>
    <li>
    <%= link_to script.content, script %>
    </li>

  <% end %>
</ul>
<%else%>
  <h1> No Essay! click below link to write one </h1>
<%end %>

<%= link_to "Add a new Essay", new_script_path %>

  

app/views/scripts/new.html.erb
<h1>Write you essay</h1>

<%= render "form", script: @script %>

app/views/scripts/show.html.erb
<h1><%= @script.user.name %></h1>
<div><%= @script.content %></div>
<ul>
  <li><%= link_to "Edit", edit_script_path(@script) %></li>
  <li><%= link_to "Destroy", script_path(@script), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<%= link_to "Home", scripts_path%>